"""initial schema

Revision ID: f222bd2af0da
Revises:
Create Date: 2026-03-07 11:47:09.615646

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "f222bd2af0da"
down_revision: str | None = None
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apikey",
        "last_used_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_apikey_id"), table_name="apikey")
    op.alter_column(
        "device",
        "notes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_index(op.f("ix_device_id"), table_name="device")
    op.drop_index(op.f("ix_devicedata_id"), table_name="devicedata")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_devicedata_id"), "devicedata", ["id"], unique=False)
    op.create_index(op.f("ix_device_id"), "device", ["id"], unique=False)
    op.alter_column(
        "device",
        "notes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.create_index(op.f("ix_apikey_id"), "apikey", ["id"], unique=False)
    op.alter_column(
        "apikey",
        "last_used_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
